- hosts: localhost
  connection: local
  vars:
    admin_group_name: "admin"
    admin_user_name: "admin"
    sudo_users_group: "wheel"
  tasks:
    - name: "Configure system clock, time, and time zone"
      include_role:
        name: ext/config-time
      vars:
        config_time_zone: "auto"
    - name: "Update pacman mirror-server-list, as required"
      include_role:
        name: ext/mirrors-update
    - name: "Configure Intel/AMD CPU-microcode updates to apply with initramfs"
      include_role:
        name: ext/cpu-ucode
      vars:
        cpu_microcode_boot_dir_path: "/ROOT/default/@/boot"
    - name: "Add and configure admin group"
      include_role:
        name: ext/add-group
      vars:
        group_name: "{{ admin_group_name }}"
    - name: "Add and configure admin user"
      include_role:
        name: ext/add-user
      vars:
        user_name: "{{ admin_user_name }}"
        user_groups:
          - "{{ admin_group_name }}"
          - "{{ sudo_users_group }}"
    - name: "Install and configure system sudo utility"
      include_role:
        name: ext/config-sudo
      vars:
        sudo_users_group: "{{ sudo_users_group }}"

