- hosts: localhost
  connection: local
  tasks:
    - name: "Update pacman mirror-server-list, as required"
      include_role:
        name: mirrors-update
    - name: "Configure Intel/AMD CPU-microcode updates to apply with initramfs"
      include_role:
        name: cpu-ucode
      vars:
        cpu_microcode_boot_dir_path: "/ROOT/default/@/boot"
    - name: "Add and configure admin group"
      include_role:
        name: admin-group
        public: yes
    - name: "Add and configure admin user"
      include_role:
        name: admin-user

