- hosts: localhost
  connection: local
  vars:
    admin_group_name: "admin"
    admin_user_name: "admin"
  tasks:
    - name: "Configure system clock, time, and time zone"
      include_role:
        name: config-time
      vars:
        config_time_zone: "auto"
    - name: "Update pacman mirror-server-list, as required"
      include_role:
        name: mirrors-update
    - name: "Configure Intel/AMD CPU-microcode updates to apply with initramfs"
      include_role:
        name: cpu-ucode
      vars:
        cpu_microcode_boot_dir_path: "/ROOT/default/@/boot"
    - name: "Add and configure admin group"
      include_role:
        name: add-group
      vars:
        group_name: "{{ admin_group_name }}"
    - name: "Add and configure admin user"
      include_role:
        name: add-user
      vars:
        user_name: "{{ admin_user_name }}"
        user_groups:
          - "{{ admin_group_name }}"
    # - name: "Install and configure system sudo utility"
    #   include_role:
    #     name: config-sudo

