- hosts: localhost
  connection: local
  vars:
    admin_user_and_group_name: "admin"
    sudo_users_group_name: "wheel"
  tasks:
    - name: "Configure system clock, time, and time zone"
      include_role:
        name: ext/config-time
      vars:
        time_zone_tz_name: "auto"
    - name: "Update pacman mirror-server-list, as required"
      include_role:
        name: ext/mirrors-update
    - name: "Configure Intel/AMD CPU-microcode updates to apply with initramfs"
      include_role:
        name: ext/cpu-ucode
      vars:
        boot_dir_path: "/ROOT/default/@/boot"
    - name: "Add sudo-users group"
      include_role:
        name: ext/add-group
      vars:
        group_name: "{{ sudo_users_group_name }}"
        is_system_group: true
    - name: "Add and configure admin user"
      include_role:
        name: ext/add-user
      vars:
        user_name: "{{ admin_user_and_group_name }}"
        user_groups:
          - "{{ sudo_users_group_name }}"
    - name: "Install and configure system sudo utility"
      include_role:
        name: ext/config-sudo
      vars:
        sudo_users_group: "{{ sudo_users_group_name }}"
        set_full_root_authority: true
        ask_password_timeout: 45
        password_prompt_timeout_minutes: 0
        use_root_umask: true
        user_for_sudo_customization: "{{ admin_user_and_group_name }}"
    - name: "Configure bash shell for interactive use"
      include_role:
        name: ext/config-bash
      vars:
        user_name: "{{ admin_user_and_group_name }}"

