- name: "Check if admin-user already exists"
  command: getent passwd {{ admin_user_def_user_name|quote }}
  register: admin_user_exists
  changed_when: admin_user_exists.rc > 2
  failed_when: admin_user_exists.rc > 2

- name: "If admin-user not exist, set password-creation action for first login"
  block:
    - name: "Create admin-user"
      user:
        name: "{{ admin_user_def_user_name }}"
      become: true
      become_user: root
    - name: "Unlock password and set password to empty"
      command: passwd -d {{ admin_user_def_user_name|quote }}
      become: true
      become_user: root
    - name: "Set password to \"expired\""
      command: chage -d 0 {{ admin_user_def_user_name|quote }}
      become: true
      become_user: root
  when: admin_user_exists.rc == 2

- name: "Add the admin-user account to the system, and configure it"
  user:
    name: "{{ admin_user_def_user_name }}"
    groups:
      - "{{ admin_group_def_group_name }}"
    append: yes
    become: true
    become_user: root

