- name: "Check if admin-user exists on the system"
  command: getent passwd {{ admin_user_def_user_name|quote }}
  # NOTE: getent returns 0 when key bound, and 2 when key not found in database
  register: admin_user_exists
  changed_when: admin_user_exists.rc == 2
  failed_when: admin_user_exists.rc != 0 and admin_user_exists.rc != 2
  notify: "set admin-user password"

- name: "Configure the admin-user account"
  user:
    name: "{{ admin_user_def_user_name }}"
    groups:
      - "{{ admin_group_def_group_name }}"
    append: yes
  become: true
  become_user: root

