- debug:
    var=ansible_hostname
  listen: "new admin-user password"

- name: "Prompt for real-time input for the new password"
  pause:
    prompt: "Enter the new admin-user password"
    echo: yes
  register: new_password
  listen: "new admin-user password"

- debug:
    var=new_password.user_input
  listen: "new admin-user password"

- name: "Create new admin-user, set password using user-input + derived salt"
  user:
    name: "{{ admin_user_def_user_name }}"
    # password: "{{ new_password.user_input | password_hash(admin_user_var_pass_hash_alg, 65534 | random(seed=ansible_hostname) | string) }}"
    password: "{{ new_password.user_input | password_hash(admin_user_var_pass_hash_alg, admin_user_def_pass_salt) }}"
  become: true
  become_user: root
  listen: "new admin-user password"

