- name: "Prompt for real-time input for the new password"
  pause:
    prompt: "Enter the new admin-user password"
    echo: yes
  register: new_password

- name: "Create new admin-user, set password using user-input + random salt"
  user:
    name: "{{ admin_user_def_user_name }}"
    password: "{{ new_password.user_input | password_hash(admin_user_var_pass_hash_alg) }}"
  become: true
  become_user: root

