- name: "Check mirror-server-list file by its modified-time"
  find:
    paths: "{{ mirrors_update_mirrors_dir }}"
    patterns: '^mirrorlist$'
    use_regex: yes
    age: "{{ mirrors_update_age }}"
  register: mirrors_found

- name: "Update mirror-server-list if it is too old"
  block:
    - name: "Install reflector package"
      pacman:
        name: reflector
        state: present
    # - name: "Create backup copy of mirror-list"
    #   copy:
    #     src: "{{ mirrors_file }}"
    #     dest: "{{ mirrors_bkup }}"
    #     force: yes
    # - name: "Find fastest servers, and replace the current mirror-list"
    #   command: reflector --country 'United States'
    #                       --latest '200'
    #                       --protocol 'http'
    #                       --protocol 'https'
    #                       --sort 'rate'
    #                       --save {{ mirrors_file|quote }}
  vars:
    mirrors_file: "{{ mirrors_update_mirrors_dir }}/{{ mirrors_update_mirrors_file }}"
    mirrors_bkup: "{{ mirrors_update_mirrors_dir }}/{{ mirrors_update_mirrors_bkup }}"
  become: true
  become_user: root
  when: mirrors_found.matched > 0

